# Generated by Django 4.2 on 2024-06-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
