# Generated by Django 4.2 on 2024-05-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_comment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments_upvotes',
        ),
        migrations.RemoveField(
            model_name='community',
            name='community_upvote',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_upvotes',
        ),
    ]
# Generated by Django 4.2 on 2024-05-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_comment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments_upvotes',
        ),
        migrations.RemoveField(
            model_name='community',
            name='community_upvote',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_upvotes',
        ),
    ]
