# Generated by Django 4.2 on 2024-06-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='url',
        ),
    ]
