# Generated by Django 4.2 on 2024-05-21 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_comment_comments_upvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_like',
        ),
    ]
