# Generated by Django 4.2 on 2024-05-21 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_remove_community_community_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_like',
            field=models.ManyToManyField(blank=True, related_name='liked_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
