# Generated by Django 4.2 on 2024-05-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_community_community_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
        migrations.AddField(
            model_name='community',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community_videos/'),
        ),
    ]
