# Generated by Django 4.2 on 2024-05-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_community_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='type',
        ),
    ]
